workflows:
  widgetkit-example-release:
    name: WidgetKitExample IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - XL AXIATA Distribution
        certificates:
          - XL AXIATA Distribution

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles --project "WidgetKitExample.xcodeproj"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "WidgetKitExample.xcodeproj" \
            --scheme "WidgetKitExample"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
